### ISSUE TITLE
OTA not working

### ISSUE THREAD

**Issue by ithinkido** [psykokwak-com/TexTime#3]
I tried today to use the OTA function on the clock to make some changes to the layout, and the esp is not showing up in the Ardiuno upload network port in the OTA section. I have checked with the basic example sketchon the same esp board, and it seems to work and is visible afterward as 

![image](https://user-images.githubusercontent.com/52834821/95735335-f6c11f00-0c84-11eb-8c74-3c51a1da6879.png)

This is using the example OTA sketch from Arduino on the same board

![image](https://user-images.githubusercontent.com/52834821/95735743-86ff6400-0c85-11eb-859e-dfc4e5cf1fec.png)

Is there something I need to enable or change to use the OTA feature ?

**Comment by psykokwak-com** [comment]
Hello,
I never tried this OTA method. Maybe there is something too old or broken on the OTA update library.
Could you try the HTTP upload OTA upgrade instead ?
