### ISSUE TITLE
Requesting info.

### ISSUE THREAD

**Issue by Tejas-MD** [psykokwak-com/TexTime#4]
Hi, I have been using a broker with URL 'mqtt.psykokwak.com'. it has been facing a downtime from recently. 
  I wanted to know if this server belongs to you and if so, requesting details about what's wrong with the server?
  Please reply. @psykokwak-com

**Comment by psykokwak-com** [comment]
Hi,
I'm sorry. This MQTT broker is hosted at home and I have internet connection issue right now.
I'll try to fix this this evening.

**Comment by Tejas-MD** [comment]
Hi, 
Thanks for the quick reply! I'm quite impressed by your projects, especially the http communication of the broker.
 Keep the amazing work going!

**Comment by Tejas-MD** [comment]
> Hi,
> I'm sorry. This MQTT broker is hosted at home and I have internet connection issue right now.
> I'll try to fix this this evening.

Any updates?

**Comment by psykokwak-com** [comment]
Hello,
My Internet provider has changed my configuration. I cannot open acces to my server on Internet. 
I tried to fix that but it will take at least few days. I'm sorry :(

**Comment by Tejas-MD** [comment]
> Hello,
> My Internet provider has changed my configuration. I cannot open acces to my server on Internet. 
> I tried to fix that but it will take at least few days. I'm sorry :(

That's sad :-(. If you can, let me know the details (is it on a raspberry pi? Is it mosquito running on it? Etc etc) so that I can try to help too? 

Also, why is it not open source? Do you plan to commercialize it? @psykokwak-com

**Comment by psykokwak-com** [comment]
Hello,
Good new. My ISP fixes my internet connection issue and my MQTT broker is back :)
